

name: Integration Test for CI

 

on:

  pull_request:

    branches:

      - main

 

jobs:

  build:

    name: CI

    runs-on: ubuntu-latest

 

    services:

      mysql:

        image: mysql:5.7

        env:

          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

        ports:

          - 3306:3306

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

 

    steps:

      - name: Checkout code

        uses: actions/checkout@v3

 

      - name: Setup Node.js

        uses: actions/setup-node@v2

        with:

          node-version: 14

 

      - name: Install dependencies

        run: npm install

 

      - name: Test MySQL Connection

        run: |

          mysql -h 127.0.0.1 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -D ${{ secrets.MYSQL_DATABASE }} -e "SHOW DATABASES;"

 

      - name: Start Node.js Application in Background

        run: |

          node app.js &

          sleep 10

 

      - name: Wait for Application to Start

        run: sleep 10

 

      - name: Run Curl Command

        run: |

          curl -X GET http://localhost:3000/healthz 

        continue-on-error: true # Continue even if the curl command fails

 

      - name: Stop Node.js Application

        run: |

          # If you're using pm2

          pm2 stop my-app || true # Adjust the app name as needed

        continue-on-error: true # Continue even if the stop command fails
