name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up MySQL
        uses: mysql/setup-mysql@v2
        with:
          mysql-version: '5.7'
          mysql-root-password: ${{ secrets.DB_ROOT_PASSWORD }}

      - name: Install dependencies
        run: npm install

      - name: Build and configure application
        run: |
          npm run build
          cp .env.example .env
          echo "DB_HOST=${DB_HOST}" >> .env
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_DATABASE=${DB_DATABASE}" >> .env

      - name: Run integration tests
        run: npm test
